export type sizeLiteral = 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl'
export type alignLiteral = 'left' | 'center' | 'right' | 'start' | 'end'
export type NamedColors =
  | 'primary'
  | 'secondary'
  | 'info'
  | 'success'
  | 'warning'
  | 'error'
  | 'unset'
export type fileSizeUnitLiteral = 'B' | 'KB' | 'MB' | 'GB'
