const languages = [
  { name: 'Arduino', value: 'arduino' },
  { name: 'Bash', value: 'bash' },
  { name: 'C', value: 'c' },
  { name: 'C++', value: 'cpp' },
  { name: 'C#', value: 'csharp' },
  { name: 'CSS', value: 'css' },
  { name: 'Diff', value: 'diff' },
  { name: 'Go', value: 'go' },
  { name: 'GraphQL', value: 'graphql' },
  { name: 'INI', value: 'ini' },
  { name: 'Java', value: 'java' },
  { name: 'JavaScript', value: 'javascript' },
  { name: 'JSON', value: 'json' },
  { name: 'Kotlin', value: 'kotlin' },
  { name: 'Less', value: 'less' },
  { name: 'Lua', value: 'lua' },
  { name: 'Makefile', value: 'makefile' },
  { name: 'Markdown', value: 'markdown' },
  { name: 'Objective-C', value: 'objectivec' },
  { name: 'Perl', value: 'perl' },
  { name: 'Plain text', value: 'plaintext' },
  { name: 'Python', value: 'python' },
  { name: 'R', value: 'r' },
  { name: 'Ruby', value: 'ruby' },
  { name: 'Rust', value: 'rust' },
  { name: 'SCSS', value: 'scss' },
  { name: 'Shell Session', value: 'shell' },
  { name: 'SQL', value: 'sql' },
  { name: 'TypeScript', value: 'typescript' },
  { name: 'Visual Basic .NET', value: 'vbnet' },
  { name: 'WebAssembly', value: 'wasm' },
  { name: 'HTML, XML', value: 'xml' },
  { name: 'YAML', value: 'yaml' }
]

export default languages
